team-MiniJin/BE

.idea/misc.xml
build.gradle

**AS-IS**
**TO-BE**
gradle  comment added

comment: gradle comment added

---

.gitignore
settings.gradle
src/main/resources/application.yaml

**AS-IS**
**TO-BE**
feat: 🗃️ application.yaml modified for mariadb
feat: 🔊 application.yaml logging updated

feat:  application.yaml updated

---

Jenkinsfile

"./gradlew"명령어를 이용한 빌드
**AS-IS**
**TO-BE**
docs: :memo: Jenkinsfile modified for gradle without installing gradle

docs: :memo: Jenkinsfile modified for gradle without installing gradle

---

Jenkinsfile

**AS-IS**
**TO-BE**
[docs: 📝 jenkins file modified for build jdk home modified](https://github.com/team-MiniJin/BE/commit/fcc8414fa7cbb1dfc5960a3cd24cdc1f0fcf8dff)

docs: :memo: jenkins file modified for build jdk home modified

---

Jenkinsfile

**AS-IS**
**TO-BE**
docs:📝 gitmessage Rev.6 updated with git-emoji

docs:📝 gitmessage Rev.6 updated with git-emoji 

---

Jenkinsfile

**AS-IS**
deploy fail error
**TO-BE**
Jenkinsfile 배포 코딩 숨김처리.
resolves: issue #14 Deploy 코딩 숨김처리로 deploy fail error 해결.

fix:🐛 Jenkinsfile modified for Deploy hide

---

src/main/java/com/minizin/travel/user/jwt/JwtAuthenticationFilter.java

- JwtUtill 클래스 이름이 TokenProvider로 변경되었습니다.
- jwt 패키지 위치를 user 패키지 안으로 변경했습니다.

refactor:♻️ refactor class name

---

src/main/java/com/minizin/travel/plan/controller/PlanController.java
src/main/java/com/minizin/travel/plan/dto/PlanBudgetDto.java
src/main/java/com/minizin/travel/plan/dto/PlanDto.java
src/main/java/com/minizin/travel/plan/dto/PlanScheduleDto.java
src/main/java/com/minizin/travel/plan/dto/ResponsePlanDto.java
src/main/java/com/minizin/travel/plan/entity/Plan.java
src/main/java/com/minizin/travel/plan/entity/PlanBudget.java
src/main/java/com/minizin/travel/plan/entity/PlanSchedule.java
src/main/java/com/minizin/travel/plan/repository/PlanBudgetRepository.java
src/main/java/com/minizin/travel/plan/repository/PlanRepository.java
src/main/java/com/minizin/travel/plan/repository/PlanScheduleRepository.java
src/main/java/com/minizin/travel/plan/service/PlanService.java
src/test/java/com/minizin/travel/plan/CreatePlanTest.java

**AS-IS**
**TO-BE**
1. Entity 생성
- Plan
- PlanSchedule
- PlanBudget
2. DTO 생성
[Request]
- PlanDto
- PlanScheduleDto
- PlanBudgetDto
[Response]
- ResponsePlanDto
3. 프로세스
- Request : PlanDto
- Response : ResponsePlanDto
- [PlanController]
- (createPlan)
- [PlanService]
- (createPlan)
- PlanDto -> Plan
- Plan DB저장
- (createPlanSchedule)
- PlanScheduleDto -> PlanSchedule
- PlanSchedule DB저장
- (createPlanBudget)
- PlanBudgetDto -> PlanBudget
- PlanBudget DB저장
- (createPlan)
- ResponsePlanDto 반환
4. 질의
- 가독성을 더 높이는 법
- 효율성을 더 높이는 법
- 그외... 자유롭게 말씀 부탁드립니다.
`{
"user_id" : 1,
"plan_name" : "테스트 계획 1",
"theme" : "테스트 1",
"start_date" : "2024-05-31",
"end_date" : "2024-06-03",
"scope" : true,
"number_of_members" : 3,
"schedule" : [
{
"schedule_date" : "2024-05-31",
"place_category" : "음식점 1", …

feat:✨#28 create plan feature

---

src/main/java/com/minizin/travel/plan/dto/ListPlanDto.java
src/main/java/com/minizin/travel/plan/service/PlanService.java

**AS-IS**
**TO-BE**
1. ListPlanDto
반환되는 응답에 plan_budget 필드 추가
2. PlanService
예산을 계산하는 private 메소드 추가
기존 commit & push 에 누락된 부분이어서 기능을 추가하였습니다.

feat:✨ #44 add feature calculate plan budget

---

Jenkinsfile

**AS-IS**
jenkinsfile : gradlew build
**TO-BE**
gradlew clean build

refactor:♻ gradlew build -> gradlew clean build

---

src/test/java/com/minizin/travel/plan/CreatePlanTest.java

**AS-IS**
**TO-BE**
이미 Application 과 Entity 내에서 삭제된 budgetMemo 필드가
테스트에서는 삭제되지 않아서 삭제 후 PR요청합니다.

fix:🐛 delete budget field in test

---

Jenkinsfile

 refactor:♻ Jenkinsfile modified for Check JDBC

---

Jenkinsfile

refactor:♻ Jenkinsfile modified

---

Jenkinsfile

refactor:♻ Jenkinsfile modified for JDBC 연결 테스트

---

Jenkinsfile

 refactor:♻ Jenkinsfile modified for JDBC 연결 테스트 /tmp에서 실행

---

Jenkinsfile

feat:✨ Jenkinsfile 배포 코드 추가.

---

Jenkinsfile

-Pjasypt.encryptor.password=minizin
**AS-IS**
**TO-BE**

refactor:♻ Jenkinsfile Build Option added for mail password

---

Jenkinsfile

remove:🔥 JenkinsFile password

---

Jenkinsfile

refactor:♻ Build, Test option added for PJASYPT key

---

Jenkinsfile

refactor:♻ Jenkinsfile Deploy modified for ssh

---

Jenkinsfile

refactor:♻ Jenkinsfile Deploy modified for ssh resolve : error } added

---

Jenkinsfile

refactor:♻ Jenkinsfile Deploy identity file removed

---

src/main/java/com/minizin/travel/plan/controller/PlanController.java
src/main/java/com/minizin/travel/plan/dto/UpcomingPlanDto.java
src/main/java/com/minizin/travel/plan/repository/PlanRepository.java
src/main/java/com/minizin/travel/plan/service/PlanService.java

**AS-IS**
**TO-BE**
로그인한 사용자의 다가오는 여행 일정을 6개 조회합니다.
사용자의 지난 여행 일정은 조회되지 않습니다.
postman을 활용한 api테스트가 진행되었습니다.
혹시 테스트 내용이 보고 싶으신 경우 말씀 부탁드립니다.

feat:✨ #39 'select upcoming plan'

---

Jenkinsfile

refactor:♻ Jenkinsfile Deploy modified for inserting BUILD_PJASYPT key

---

Jenkinsfile

refactor:♻ Jenkinsfile Deploy modified for ssh key error Rev1,2

---

Jenkinsfile

refactor:♻ Jenkinsfile Deploy modified for ssh key error Rev3

---

src/main/java/com/minizin/travel/config/AppConfig.java
src/main/java/com/minizin/travel/config/SecurityConfig.java
src/main/java/com/minizin/travel/tour/controller/TourController.java
src/main/java/com/minizin/travel/tour/controller/TourInfoController.java
src/main/java/com/minizin/travel/tour/domain/dto/TourAPIDto.java
src/main/java/com/minizin/travel/tour/domain/entity/TourAPI.java
src/main/java/com/minizin/travel/tour/domain/repository/TourAPIRepository.java
src/main/java/com/minizin/travel/tour/service/TourInfoService.java
src/main/java/com/minizin/travel/tour/service/TourService.java

TourService, TourController PostManAPI Test finished
**AS-IS**
**TO-BE**
api-tour :동기 -> 비동기 GET Code resolve: #42 
GET searchkeyword

feat:✨api-tour :동기 -> 비동기 GET Code resolve : #42

---

Jenkinsfile

feat:✨Jenkinsfile Deploy modified for killing 8080,java service

---

Jenkinsfile

SSH connection or file transfer failed: hudson.AbortException: script returned exit code 255
**AS-IS**
**TO-BE**

fix:🐛 Jenkinsfile modified for ssh connection error Rev1

---

Jenkinsfile

env.BRANCH_NAME == 'develop' -> env.BRANCH_NAME == 'develop' || env.BRANCH_NAME.contains('jenkins')
**AS-IS**
**TO-BE**

fix:🐛 Jenkinsfile modified for ssh connection error Reve

---

Jenkinsfile

fix:🐛 Jenkinsfile modified for ssh connection error Rev3

---

Jenkinsfile

${NGINX_MINIJIN} -> ${env.NGINX_MINIJIN}
**AS-IS**
**TO-BE**

fix:🐛 Jenkinsfile modified for ssh connection error Rev4

---

Jenkinsfile

Triple Quotes (""") modified
Escape Dollar Signs (\$) added
**AS-IS**
**TO-BE**

fix:🐛 Jenkinsfile modified for ssh connection error Rev5

---

Jenkinsfile

fix:🐛 Jenkinsfile modified for ssh connection error Rev6

---

Jenkinsfile

fix:🐛 Jenkinsfile modified for ssh connection error Rev7

---

Jenkinsfile

fix:🐛 Jenkinsfile modified for ssh connection error Rev8

---

src/main/java/com/minizin/travel/plan/controller/PlanController.java
src/main/java/com/minizin/travel/plan/dto/ResponseDeletePlanDto.java
src/main/java/com/minizin/travel/plan/service/PlanService.java

**AS-IS**
**TO-BE**
plan id값을 요청 받아
해당 plan id 를 가지는 plan
- 해당 plan id 를 가지는 schedule
- 위 schedule id 를 가지는 budget 모두 삭제
Postman 을 통한 API테스트 완료

feat:✨ /plans/{plan_id} #47 delete plan

---

Jenkinsfile

fix:🐛 Jenkinsfile modified for ssh connection error Rev9

---

Jenkinsfile

fix:🐛 Jenkinsfile modified for ssh connection error Rev10

---

Jenkinsfile

fix:🐛 Jenkinsfile modified for ssh connection error Rev11

---

Jenkinsfile

fix:🐛 Jenkinsfile modified for ssh connection error Rev12

---

Jenkinsfile

fix:🐛 Jenkinsfile modified for ssh connection error Rev13

---

Jenkinsfile

fix:🐛 Jenkinsfile modified for ssh connection error Rev14

---

src/main/java/com/minizin/travel/plan/controller/PlanController.java
src/main/java/com/minizin/travel/plan/dto/PlanDto.java
src/main/java/com/minizin/travel/plan/dto/PlanScheduleDto.java
src/main/java/com/minizin/travel/plan/dto/ResponsePlanDto.java
src/main/java/com/minizin/travel/plan/service/PlanService.java

**AS-IS**
Like, numbeOfLike 필드 존재
calculateTotalPlanBudget : Plan 패키지 내 private 
**TO-BE**
1. 400 에러 추가
- 데이터 min/max 값이 일치하지 않는 경우
- 여행 날짜 : 1 ~ 7일
- 장소 개수 : 1일 이상
- 장소 이름 : 1 ~ 20자
- 장소 메모 : 60자 이하
- 총 예산 : 100,000,000원 이하
2. 실패 message 추가
3. numberOfLikes 필드 저장 부분 제거(현재 메소드/기능별로 제거중)
4. calculateTotalPlanBudget 는 타 패키지에서 사용하게 되어 public 변경
Postman을 활용한 API 테스트 완료

refactor:♻️ #87 /plans [POST] Refactoring

---

src/main/java/com/minizin/travel/config/CorsMvcConfig.java
src/main/java/com/minizin/travel/config/SecurityConfig.java

refactor:♻️ add cors config

---

src/main/java/com/minizin/travel/like/dto/ResponseSelectLikedPlansDto.java
src/main/java/com/minizin/travel/like/dto/SelectLikedPlansDto.java

fix:🐛 delete like service

---

src/main/java/com/minizin/travel/config/SecurityConfig.java
src/main/java/com/minizin/travel/user/jwt/JwtAuthenticationFilter.java

refactor:♻️ add ignore path

---

src/main/java/com/minizin/travel/config/CorsMvcConfig.java
src/main/java/com/minizin/travel/config/SecurityConfig.java

refactor:♻️ refactor cors config

---

src/main/java/com/minizin/travel/config/CorsMvcConfig.java
src/main/java/com/minizin/travel/config/SecurityConfig.java

refactor:♻️ rollback cors config

---

src/main/java/com/minizin/travel/user/oauth2/CustomSuccessHandler.java
src/main/resources/application-oauth.yml

refactor:♻️ refactor uri

---

src/main/java/com/minizin/travel/global/GlobalExceptionHandler.java
src/main/java/com/minizin/travel/global/enums/ValidationErrorCode.java
src/main/java/com/minizin/travel/user/domain/enums/JwtErrorCode.java
src/main/java/com/minizin/travel/user/domain/enums/UserErrorCode.java
src/main/java/com/minizin/travel/user/domain/exception/CustomUserException.java
src/main/java/com/minizin/travel/user/jwt/JwtExceptionFilter.java
src/main/java/com/minizin/travel/user/service/AuthService.java
src/test/java/com/minizin/travel/user/service/AuthServiceTest.java

- 전역 예외 핸들러가 추가되었습니다.
- 회원가입 시 발생하는 예외를 상태코드와 메세지로 응답합니다.
- 유효성 검사 시 발생하는 예외를 상태코드와 메세지로 응답합니다.

feat:✨ add global exception handler

---

src/main/java/com/minizin/travel/plan/controller/PlanController.java

**AS-IS**
**TO-BE**
FE 테스트 연동을 위한 로그인 연동 제거
파라미터 @RequestParam 으로 받을 수 있게 수정

refactor:♻️ /plans [GET] request parameter 수정

---

src/main/java/com/minizin/travel/plan/service/PlanService.java

**AS-IS**
**TO-BE**
현재 테스트 미진행으로 인한 로그인 연동 제거
일정당 스케줄 1개 이상인 조건 삭제

remove:🔥 스케줄 개수 1개 이상 필수 조건 삭제

---

src/main/java/com/minizin/travel/global/GlobalExceptionHandler.java
src/main/java/com/minizin/travel/user/domain/enums/MailErrorCode.java
src/main/java/com/minizin/travel/user/domain/exception/CustomMailException.java
src/main/java/com/minizin/travel/user/service/MailService.java
src/test/java/com/minizin/travel/user/service/MailServiceTest.java

- 메일 관련 예외가 전역 핸들러에 추가되었습니다.
- 임시 비밀번호 관련 테스트 코드가 추가되었습니다.

feat:✨ mail error handling

---

Jenkinsfile

fix:🐛 Jenkinsfile modified for when  PR is merged the Deploy starting.

---

src/main/java/com/minizin/travel/tour/controller/TourInfoController.java

refactor:♻ api-tour tourinfoContoller Common method refactoring

---

src/main/java/com/minizin/travel/tour/controller/TourInfoController.java
src/main/java/com/minizin/travel/tour/domain/repository/TourAPIRepository.java
src/main/java/com/minizin/travel/tour/service/TourInfoService.java

tour - GET Service finished
tour/info - GET Service finished
resolve : #114
**AS-IS**
**TO-BE**

feat:✨api-tour searchKeyword1 GET Service finished

---

src/main/java/com/minizin/travel/plan/controller/OtherPlanController.java
src/main/java/com/minizin/travel/plan/dto/DetailPlanDto.java
src/main/java/com/minizin/travel/plan/dto/OthersListPlanDto.java
src/main/java/com/minizin/travel/plan/dto/OthersListPlanScheduleDto.java
src/main/java/com/minizin/travel/plan/dto/PopWeekPlanDto.java
src/main/java/com/minizin/travel/plan/dto/ResponseOthersPlanDto.java
src/main/java/com/minizin/travel/plan/service/OtherPlanService.java
src/main/java/com/minizin/travel/plan/service/PlanService.java

틀만 추가 : #48 #58 #106
기능까지 추가 : #129
**AS-IS**
**TO-BE**
**틀 추가**
#48 다른 사람의 여행 일정 조회(최신순)
#58 다른 사람의 여행 일정 조회(스크랩순)
#106 금주 인기 여행 일정 조회
**기능 추가**
#129 다른 사람의 여행 일정 상세 보기
**refactoring**
planService 의 method 분리

feat:✨ add #48 #58 #106 #129

---

src/main/java/com/minizin/travel/user/oauth2/CustomSuccessHandler.java
src/main/resources/application-oauth.yml

서버 도메인 변경
- protocol: http -> https
- port: 20280 -> 23080

refactor:♻️ refactor config

---

src/main/java/com/minizin/travel/config/CorsMvcConfig.java
src/main/java/com/minizin/travel/config/SecurityConfig.java

cors : 프론트 배포 주소를 허용 오리진에 추가했습니다

feat:✨ add allowed origin

---

src/main/java/com/minizin/travel/user/domain/enums/UserErrorCode.java
src/main/java/com/minizin/travel/user/service/UserService.java
src/test/java/com/minizin/travel/user/service/UserServiceTest.java

사용자 관련 예외에 대한 응답을 받을 수 있습니다.
**TO-BE**

feat:✨user error handling

---

src/main/java/com/minizin/travel/user/oauth2/CustomSuccessHandler.java

test:✅ cookie error test

---

src/main/java/com/minizin/travel/user/controller/AuthController.java

feat:✨ add log

---

src/main/java/com/minizin/travel/plan/controller/OtherPlanController.java
src/main/java/com/minizin/travel/plan/dto/OthersListPlanDto.java
src/main/java/com/minizin/travel/plan/dto/ResponseOthersPlanDto.java
src/main/java/com/minizin/travel/plan/repository/PlanRepository.java
src/main/java/com/minizin/travel/plan/service/OtherPlanService.java

북마크순, 최신순 추가
추후 region 관련 기능 추가 필요
**AS-IS**
**TO-BE**
다른 사람의 일정 목록 조회(최신순/북마크순)에
파라미터로 받는 theme 값을 추가하였습니다.
Postman으로 테스트 완료
로컬 빌드 완료

feat:✨ #48 #58 다른 사람의 일정 목록 조회

---

src/main/java/com/minizin/travel/user/controller/AuthController.java

test:✅ add log

---

src/main/java/com/minizin/travel/user/oauth2/CustomSuccessHandler.java

feat:✨ add same site option

---

src/main/java/com/minizin/travel/user/oauth2/CustomSuccessHandler.java

feat:✨ add secure option

---

src/main/java/com/minizin/travel/plan/dto/ResponseOthersPlanDto.java

**AS-IS**
**TO-BE**
다른 사람 일정 조회 시 무한 스크롤 기능 중
조회할 데이터가 없을 시 next_cursor  필드 제거
Postman 을 이용한 API 테스트 완료
로컬 빌드 완료

fix:🐛 #151 조회할 데이터가 없을 시 next_cursor 필드 제거

---

src/main/java/com/minizin/travel/plan/dto/OthersListPlanScheduleDto.java
src/main/java/com/minizin/travel/plan/service/PlanService.java

**AS-IS**
**TO-BE**
스케줄 1일차, 2일차 계산 메커니즘 착오로 인하여 수정
schedule 필드의 case(->snake_case) 변경

fix:🐛 schedule days(1일차, 2일차...) 수정

---

src/main/java/com/minizin/travel/plan/controller/PlanController.java
src/main/java/com/minizin/travel/plan/dto/PlanBudgetDto.java
src/main/java/com/minizin/travel/plan/dto/PlanScheduleDto.java
src/main/java/com/minizin/travel/plan/dto/ResponsePlanDto.java
src/main/java/com/minizin/travel/plan/service/PlanService.java

**AS-IS**
**TO-BE**
기존 계획(스케줄, 예산 포함) 을 복사하여 나의 계획 만들기
- 계획 시작 일자 -> 오늘
- 계획 종료 일자 -> 오늘 일자에 기존 계획 일자를 더함
- 스크랩 수 초기화 
Postman 을 활용한 API 테스트 완료
로컬 빌드 완료

feat:✨ #107 기존 일정 복사하여 나의 일정 생성

---

src/main/java/com/minizin/travel/config/SecurityConfig.java
src/main/java/com/minizin/travel/user/jwt/JwtAuthenticationFilter.java

refactor:♻️ refactor authorization path

---

src/main/java/com/minizin/travel/plan/dto/DetailPlanDto.java
src/main/java/com/minizin/travel/plan/dto/ResponseEditPlanDto.java
src/main/java/com/minizin/travel/plan/dto/ResponsePlanDto.java
src/main/java/com/minizin/travel/plan/repository/PlanRepository.java
src/main/java/com/minizin/travel/plan/service/OtherPlanService.java
src/main/java/com/minizin/travel/plan/service/PlanService.java
src/main/java/com/minizin/travel/scrap/service/ScrapService.java

**AS-IS**
**TO-BE**
fix:🐛 others 로그인 관련 부분 제외 
fix:🐛 plan id 가 없는 경우, 메시지 응답
- 나의 PLAN 상세보기
- 다른 사람 PLAN 상세보기
- PLAN 수정하기
- PLAN 복사하기

fix:🐛 others 로그인 관련 부분 제외 , plan id 가 없는 경우, 메시지 응답

---

src/main/java/com/minizin/travel/plan/repository/PlanRepository.java
src/main/java/com/minizin/travel/plan/service/PlanService.java

**AS-IS**
D-0 계획은 포함하지 않음
**TO-BE**
D-0 계획 포함함

fix:🐛 다가오는 여행 일정에 D-0 계획 포함

---

src/main/java/com/minizin/travel/plan/dto/ResponsePlanDto.java
src/main/java/com/minizin/travel/scrap/dto/ResponseCreateScrapPlanDto.java

**AS-IS**
기존 RuntimeException 으로 응답 시 프론트에서 kakao 로 응답 받음
**TO-BE**
해당 예외를 모두 ResponseBody 에 담아 응답

fix:🐛 북마크 관련 예외처리를 응답 메시지로 응답

---

src/main/java/com/minizin/travel/tour/controller/TourController.java
src/main/java/com/minizin/travel/tour/domain/dto/TourAPIDto.java
src/main/java/com/minizin/travel/tour/domain/entity/TourAPI.java
src/main/java/com/minizin/travel/tour/domain/repository/TourAPIRepository.java
src/main/java/com/minizin/travel/tour/service/TourInfoService.java
src/main/java/com/minizin/travel/tour/service/TourService.java

TourAPI Entity update with detail Common GET Data
resolve : #164
**AS-IS**
**TO-BE**

feat:✨api-tour detail Common GET Service,controller

---

src/main/resources/application.yml
src/main/resources/logback-spring.xml

feat:✨logger setting creating resources/logback-spring.xml

---

src/main/java/com/minizin/travel/tour/service/TourService.java
src/main/resources/application.yml
src/main/resources/logback-spring.xml

**AS-IS**
**TO-BE**
chore:👷 logs level modified debug -> INFO
refactor:♻ api-tour 비동기, 배치, 에러 관리

chore:👷 logs level modified & refactor:♻ api-tour 비동기, 배치, 에러 관리

---

src/main/java/com/minizin/travel/user/service/CustomOAuth2UserService.java

소셜 로그인 사용자가 로그인할 때 마다 닉네임을 재 설정하지 않도록 수정했습니다.

refactor:♻️ refactor oauth2 user setting

---

src/main/java/com/minizin/travel/plan/controller/OtherPlanController.java

**AS-IS**
/plans/others/details/{plan_id}
**TO-BE**
/plans/others/{plan_id}
로 수정합니다.

feat:✨ others detail plan path 수정

---

src/main/java/com/minizin/travel/global/GlobalExceptionHandler.java

여러 가지 상황에 맞는 응답을 전달하기 위해 예외 핸들러를 추가했습니다.

feat:✨ add exception handler

---

src/main/java/com/minizin/travel/config/SecurityConfig.java
src/main/java/com/minizin/travel/user/jwt/JwtAuthenticationFilter.java

refactor:♻️ refactor authentication path

---

src/main/java/com/minizin/travel/plan/controller/OtherPlanController.java
src/main/java/com/minizin/travel/plan/repository/PlanRepository.java
src/main/java/com/minizin/travel/plan/service/OtherPlanService.java

**AS-IS**
**TO-BE**
search 파라미터를 추가함으로써 쿼리문을 새로 작성
파라미터 null 값 처리
https://developer-joon.tistory.com/171
String.isEmpty() 가 아닌 StringUtils.isEmpty 을 쓰는 이유는 null 에 안전하기 때문입니다.
(https://velog.io/@posasac/Java-StringUtils.isEmpty)

fix:🐛 다른 사람의 여행 일정 조회 시 search 파라미터 추가

---

src/main/java/com/minizin/travel/plan/controller/PlanController.java
src/main/java/com/minizin/travel/plan/dto/DetailPlanDto.java
src/main/java/com/minizin/travel/plan/repository/PlanRepository.java
src/main/java/com/minizin/travel/plan/service/OtherPlanService.java
src/main/java/com/minizin/travel/plan/service/PlanService.java

**AS-IS**
**TO-BE**
#125 login 한 user의 정보를 찾아 활용하기

#125 login 한 user의 정보를 찾아 활용하기

---

src/main/java/com/minizin/travel/plan/service/OtherPlanService.java

feat:✨ } 오기입 정정

---

src/main/java/com/minizin/travel/plan/service/OtherPlanService.java
src/main/java/com/minizin/travel/scrap/controller/ScrapController.java
src/main/java/com/minizin/travel/scrap/service/ScrapService.java

**AS-IS**
**TO-BE**
#125 feat:✨ scrap 에 login 연동
다른 사람 여행 일정 조회 시 닉네임 가져오는 부분 추가

feat:✨ scrap 에 login 연동

---

src/main/java/com/minizin/travel/plan/dto/DetailPlanDto.java

**AS-IS**
@JsonInclude(JsonInclude.Include.NON_DEFAULT)
**TO-BE**
@JsonInclude(JsonInclude.Include.NON_NULL)

fix:🐛 DetailPlanDto 의 필드는 null 이 아닐 경우 전부 출력

---

src/main/java/com/minizin/travel/scrap/controller/ScrapController.java
src/main/java/com/minizin/travel/scrap/dto/ResponseCheckScrapedPlanDto.java
src/main/java/com/minizin/travel/scrap/service/ScrapService.java

**AS-IS**
**TO-BE**
기존 내용 메소드 분리

feat:✨ 이미 스크랩한 plan 인지 확인

---

src/main/java/com/minizin/travel/plan/service/OtherPlanService.java

feat:✨ 다른 사람의 일정 조회 에러 수정

---

src/main/java/com/minizin/travel/scrap/service/ScrapService.java

**AS-IS**
본인의 plan 스크랩하기 비허용
**TO-BE**
본인의 plan 스크랩하기 허용

fix:🐛 본인의 plan 스크랩하기 허용

---

src/main/java/com/minizin/travel/user/oauth2/CustomSuccessHandler.java

refactor:♻️ refactor social login redirect path

---

src/main/java/com/minizin/travel/user/oauth2/CustomSuccessHandler.java

refactor:♻️ refactor social login path

---

src/main/java/com/minizin/travel/scrap/service/ScrapService.java

fix:🐛 scrapservice 내 user 관련 예외처리

---

src/main/java/com/minizin/travel/tour/service/TourService.java

fix:🐛 api-tour detailcommon null 에러 해결 Rev01

---

src/main/java/com/minizin/travel/tour/service/TourService.java

entity가 새로 만들어져 저장되는 코드 -> entity update 후 저장되는 코드로 수정
**AS-IS**
**TO-BE**

fix:🐛 api-tour detailcommon entity update누락 error 코드 수정

---

src/main/java/com/minizin/travel/tour/controller/TourController.java
src/main/java/com/minizin/travel/tour/domain/repository/TourAPIRepository.java
src/main/java/com/minizin/travel/tour/service/TourInfoService.java
src/main/java/com/minizin/travel/tour/service/TourService.java

**AS-IS**
searchkeyword : addr1기반  검색조건
areaBasedList : 정렬 기준없는 지역 검색조건
**TO-BE**
searchkeyword :  addr1 & title 기반 검색조건 & areaCode,contentTypeId, sigunguCode 입력시 해당 정보 위주 검색조건 & 한글 title기준 검색 조건 추가.
areaBasedList : 한글 title기준 검색 조건 추가. 
areaBasedListSingle : 특정 위치 기반 자료들을 대량으로 공공데이터에서 가져올 수 있는 코드 추가.

refactor:♻ api-tour areaBasedList, searchKeyword service modified for using webpage.

---

src/main/java/com/minizin/travel/tour/controller/TourInfoController.java
src/main/java/com/minizin/travel/tour/service/TourInfoService.java

refactor:♻ api-tour tourInfo, fix:🐛 api-tour getTourDataByAreaCode 

---

src/main/java/com/minizin/travel/tour/controller/TourInfoController.java
src/main/java/com/minizin/travel/tour/domain/dto/TourAPIDto.java
src/main/java/com/minizin/travel/tour/domain/repository/TourAPIRepository.java
src/main/java/com/minizin/travel/tour/service/TourInfoService.java
src/main/java/com/minizin/travel/tour/service/TourService.java
src/main/resources/logback-spring.xml

fix:🐛 api-tour 지역목록 불러오기,시군구목록 불러오기, 여행지목록 불러오기,상제정보 불러오기 해결완료

---

src/main/java/com/minizin/travel/tour/controller/TourController.java
src/main/java/com/minizin/travel/tour/domain/dto/TourAPIDto.java
src/main/java/com/minizin/travel/tour/domain/repository/TourAPIRepository.java
src/main/java/com/minizin/travel/tour/service/TourInfoService.java
src/main/java/com/minizin/travel/tour/service/TourService.java

code 에 도시 & 도별 이름
sigungu에 각 도시별 군구 이름
resolve: #203
**AS-IS**
**TO-BE**

fix:🐛 api-tour sigungucode만 가져오는 코드 완성

---

src/main/java/com/minizin/travel/tour/service/TourInfoService.java

fix:🐛 api-tour searchkeyword 지역 선택시 검색 안되는 에러 해결

---

build.gradle
src/main/java/com/minizin/travel/config/CorsMvcConfig.java
src/main/java/com/minizin/travel/config/SecurityConfig.java
src/main/java/com/minizin/travel/config/SwaggerConfig.java
src/main/java/com/minizin/travel/tour/controller/TourController.java
src/main/resources/application.yml

**AS-IS**
http://localhost:8080/swagger-ui/index.html 
에서 api doc 확인가능
**TO-BE**

api-doc : Swagger 관련 코드 추가완료. 

---

src/main/java/com/minizin/travel/config/CorsMvcConfig.java
src/main/java/com/minizin/travel/config/SwaggerConfig.java
src/main/resources/application.yml

feat:✨api-doc swagger 외부주소에서 접속 가능하도록 코드 수정

---

.idea/misc.xml
src/main/java/com/minizin/travel/board/controller/BoardController.java
src/main/java/com/minizin/travel/board/dto/AddBoardRequest.java
src/main/java/com/minizin/travel/board/dto/AddBoardResponse.java
src/main/java/com/minizin/travel/board/dto/AddBookmarkRequest.java
src/main/java/com/minizin/travel/board/dto/UpdateBoardRequest.java
src/main/java/com/minizin/travel/board/entity/Board.java
src/main/java/com/minizin/travel/board/exception/BoardException.java
src/main/java/com/minizin/travel/board/repository/BoardRepository.java
src/main/java/com/minizin/travel/board/service/BoardService.java
src/main/java/com/minizin/travel/chat/controller/ChatController.java
src/main/java/com/minizin/travel/chat/controller/ChatRoomController.java
src/main/java/com/minizin/travel/chat/exception/ChatRoomException.java
src/main/resources/application.yaml
src/test/java/com/minizin/travel/board/service/BoardServiceTest.java
src/test/resources/application-test.properties

**AS-IS**
chat 에러코드명 변경, 매핑 주소 변경
**TO-BE**
동행자 구하기(게시판) 기능(모두 보기, 유저 id 당 보기, 게시글 만들기, 수정, 삭제) 
동행자 구하기 서비스 테스트 통과

[feat] 동행자 구하기 구현
